### ISSUE TITLE
Create Branch

### ISSUE THREAD

**Issue by gtnarg** [jdereg/n-cube-editor#286]
I have the editor up and running. When I try to create a branch - I can see a bunch of status messages momentarily (I think they are errors) but they disappear. When I look at catalina.log I'm not seeing any errors. The branch is not created.

Any suggestions on what else to do to diagnose the issue?

Thanks,
Grant

**Comment by jdereg** [comment]
A default branch should initially be created.  Inside that branch, create a single n-cube (new n-cube).  Make sure you have 'default branch' not 'HEAD' selected on the left-side of the screen.

Once you have successfully created an n-cube, you can then create a branch.  This is a boot-strap (getting started) special case - getting one n-cube created into your database first.  Once you have that completed, then you can create other apps and branches on those apps.

**Comment by gtnarg** [comment]
It doesn't look like a default branch was created (the following shows when I select HEAD).  The other two dropdowns are also empty (if that is of any consequence).

![image](https://cloud.githubusercontent.com/assets/1252704/18833387/55a56142-83be-11e6-8d18-a1671c7a663f.png)

**Comment by jdereg** [comment]
This was fixed a while ago - starting NCE against an empty database - it now recognizes this on start up and populates the minimal n-cubes to get up and running.
